-- Migration: Remove all fake ranking data created by the previous migration
-- This ensures only authentic ranking data is displayed

BEGIN;

-- 1. Delete all artificially created keyword rankings for Mister Candle
-- These were generated by the migration and don't represent real search results
DELETE FROM keyword_rankings 
WHERE brand_keyword_id IN (
  SELECT id FROM brand_keywords WHERE brand_name = 'Mister Candle'
)
AND created_at >= CURRENT_DATE; -- Only delete recent artificial data

-- 2. Remove the artificial brand ranking summary
DELETE FROM brand_ranking_summary 
WHERE brand_name = 'Mister Candle' 
AND check_date_only = CURRENT_DATE;

-- 3. Keep only the real, verified keyword data without fake rankings
-- The brand_keywords table will remain with real search volumes,
-- but without artificial ranking positions

COMMIT;

-- Verify cleanup
SELECT 
  'Fake ranking data removed' as status,
  COUNT(*) as remaining_keywords,
  SUM(search_volume) as total_search_volume
FROM brand_keywords 
WHERE brand_name = 'Mister Candle' 
AND is_active = true;